name: Publish Image

on:
  push:
    tags:
      - '*'
    branches-ignore:
      - '*'

env:
  FULL_TAG: ${GITHUB_REF##*/}
  LATEST_TAG: ${FULL_TAG%-*}-latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v3

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.FULL_TAG }},${{ env.LATEST_TAG }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
